### ISSUE TITLE
[Bug] When providing a focusNode to CodeInput() an error occurs.

### ISSUE THREAD

**Issue by HelgeSverre** [Rahiche/flutter_code_input#17]
I am getting an error for version ```1.0.2```

## Example code:

```dart
import 'package:code_input/code_input.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class PhoneVerificationScreen extends StatefulWidget {
  const PhoneVerificationScreen({Key key}) : super(key: key);

  @override
  _PhoneVerificationScreenState createState() =>
      _PhoneVerificationScreenState();
}

class _PhoneVerificationScreenState extends State<PhoneVerificationScreen> {
  FocusNode _focusNode = FocusNode();

  @override
  void initState() {
    super.initState();

    // Request focus to the focusNode.
    FocusScope.of(context).requestFocus(_focusNode);
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(left: 25, right: 25),
      child: CodeInput(
        length: 4,
        focusNode: _focusNode, // <-- This causes the error
        keyboardType: TextInputType.number,
        builder: _codeInputBuilder(),
        onFilled: (code) {
          // Verify the code and send user to "dashboard"
        },
      ),
    );
  }

  _codeInputBuilder() {
    return CodeInputBuilders.containerized(
      totalSize: Size(60, 50),
      emptySize: Size(50, 50),
      emptyDecoration: BoxDecoration(
        border: Border.all(color: Colors.grey[300]),
        borderRadius: BorderRadius.circular(4),
        color: Color(0xFFF9F9F9),
      ),
      emptyTextStyle: TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.bold,
        color: Colors.pink,
      ),
      filledSize: Size(50, 50),
      filledDecoration: BoxDecoration(
        border: Border.all(color: Colors.red),
        borderRadius: BorderRadius.circular(4),
        color: Colors.white,
      ),
      filledTextStyle: TextStyle(
        fontSize: 20,
        fontWeight: FontWeight.bold,
        color: Colors.pink,
      ),
    );
  }
}

```

## Image 

![image](https://user-images.githubusercontent.com/1089652/58862522-1e779e80-86b1-11e9-8eb1-30df559ca064.png)

## Log output
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter (16437): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16437): The following _CompileTimeError was thrown building PhoneVerificationScreen(dirty, state:
I/flutter (16437): _PhoneVerificationScreenState#68098):
I/flutter (16437): 'package:code_input/code_input.dart': error: Not a constant expression: unexpected kernel tag
I/flutter (16437): ConstructorInvocation (31)
I/flutter (16437): 
I/flutter (16437): When the exception was thrown, this was the stack:
I/flutter (16437): #0      _PhoneVerificationScreenState._buildVerificationInput (package:tjommi/screens/auth/phone_verification.dart:122:9)
I/flutter (16437): #1      _PhoneVerificationScreenState.build (package:tjommi/screens/auth/phone_verification.dart:102:53)
I/flutter (16437): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (16437): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (16437): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (16437): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #7      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (16437): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #17     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (16437): #18     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (16437): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #22     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (16437): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #28     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (16437): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (16437): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (16437): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #44     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (16437): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (16437): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (16437): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #60     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (16437): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #64     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (16437): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #66     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (16437): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #70     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (16437): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (16437): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (16437): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (16437): #74     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (16437): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (16437): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (16437): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (16437): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (16437): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter (16437): #81     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (16437): #82     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (16437): #83     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (16437): (elided one frame from package dart:async-patch)
I/flutter (16437): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 23 of 634 libraries in 1 404ms.
****
```

## Flutter Doctor

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale nb-NO)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • ANDROID_SDK_ROOT = C:\Android\android-sdk
    • Java binary at: C:\Users\Helge Sverre\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\Helge Sverre\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\Helge Sverre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

Does anyone have any idea what might be causing this error?

**Comment by marcelgarus** [comment]
Whoa, that should not have happened. 😨
I implemented a fix at #18, would you mind testing it?

**Comment by HelgeSverre** [comment]
@marcelgarus  How do i go about testing a hotfix branch as the "current version" in the pubspec.yml file?

**Comment by marcelgarus** [comment]
In your `pubspec.yaml`, you can define a custom git path:
```yaml
dependencies:
  flutter_code_input:
    git:
      url: git://github.com/marcelgarus/flutter_code_input.git
      ref: hotfix-17-focus-node
```

**Comment by HelgeSverre** [comment]
That fix seems to work, just tried it out.

**Comment by marcelgarus** [comment]
Wonderful! 🎉
@Rahiche This should be updated on pub.dev.

**Comment by Rahiche** [comment]
It's on pub now.
According to semver we have to make a 1.0.3 because this is a critical bug
BTW @marcelgarus  we need automated tests I can write some unit & widget tests next week.
